apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.imageName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.imageName }}
  template:
    metadata:
      labels:
        app: {{ .Values.imageName }}
    spec:
      containers:
      - name: {{ .Values.imageName }}
        image: "{{ .Values.registry }}/{{ .Values.repo }}/{{ .Values.imageName }}:{{ .Values.imageTag }}"
        env:
        {{- range $key, $value :=  .Values.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306