apiVersion: v1
kind: Service
metadata:
  name: mydevopsapp-service
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: mydevopsapp-app
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: {{ .Values.protocol }}